language: node_js
node_js:
  - "10.15.0"

script:
  - yarn build
  - echo 'perfessic.com' > ./dist/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  on:
    branch: master